name: specviewenv
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy=2.4.3
  - scipy=1.17.1
  - numba=0.65.0
  - llvmlite=0.47.0
  - matplotlib=3.10.9
  - pyqt=5.15.10
  - opencv
  - spectral
  - reportlab=4.4.10
  - pip
  - pip:
      - hylite==1.36
      - gfit==0.2